pipeline{
        agent any
            environment{
                DB_PASSWORD = credentials('DATABASE_PASSWORD')
            }
        stages{
            stage('Clone Repo'){
                steps{
                    echo "new branch for using snippet generator"
                    git 'https://gitlab.com/qacdevops/chaperootodo_client.git'
                }
            }
            stage('Install Docker & Docker Compose'){
                steps{
                    //sh 'sudo apt-get update'
                    //sh 'sudo apt install curl -y jq'
                    sh 'curl https://get.docker.com | sudo bash'
                    //sh 'sudo usermod -aG docker "$(whoami)"'
                    
                    
                    sh 'sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                    sh 'sudo chmod +x /usr/local/bin/docker-compose'
                    
                }
            }
            stage('Deploy'){
                steps{
                    sh 'sudo docker-compose -f docker-compose.yaml pull  && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose -f docker-compose.yaml up -d'
                }
            }
        }
}