version: "3.8"
services:
  flask-app:
    build: ./trio-task/flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./trio-task/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:
    build: ./trio-task/db
    target: 3306
    published: 3306
    protocol: tcp