- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/sqlite/sqlite.git
      dest: /home/ubuntu/repos/
      clone: yes
      update: yes