- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
    register: nginxcachetime
    #failed when: "nginxcachetime.cache_update_time > 1"
  - name: nginx cache debug
    debug:
      var: nginxcachetime
    
    
  # - name: Copy nginx file over
  #   copy:
  #     src: nginx.conf
  #     dest: /etc/nginx/nginx.conf
  #   register: nginx_config

  # - name: Copy nginx file info
  #   debug:
  #     msg: "{{ nginx_config }}"
    
  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true

  - name: Uninstall nginx
    apt:
      name: nginx
      state: absent
      autoremove: yes