- hosts: localhost
  become: true
  tasks: 
    - name: "Create swarm manager"
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: "docker_info.stdout.find('Swarm: inactive') > 0"

    - name: "Get manager ip"
      copy: 
        content: "{{ ansible_default_ipv4.address }}"
        dest: "/tmp/manager-ip"

    - name: "Get manager token"
      shell: docker swarm join-token -q manager
      register: manager_token
    - copy:
        content: "{{ manager_token.stdout }}"
        dest: "/tmp/manager-token"
    
    - name: "Get worker token"
      shell: docker swarm join-token -q worker
      register: worker_token
    - copy:
        content: "{{ worker_token.stdout }}"
        dest: "/tmp/worker-token" 

- hosts: all
  become: true
  tasks: 
    - name: "Join"
      shell: "docker swarm join --token {{ lookup('file', '/tmp/manager-token') }} {{ lookup('file', '/tmp/manager-ip') }}:2377" 
      
      