- hosts: all
become: yes
gather_facts: false
tasks:
- name: Install docker packages
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add Docker s GPG key for ubuntu from official site
apt_key:
  url: https://download.docker.com/linux/ubuntu/gpg
  state: present
tags:
  - docker

- name: Configure Docker for ubuntu stable repository
remote_user: ansible_ubuntu_demo
apt_repository:
  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  state: present
  update_cache: yes
tags:
  - docker